# Generated by Django 5.1 on 2024-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="running_time",
            field=models.DurationField(),
        ),
    ]
